[project]
name = "controlled-rsde"
version = "0.1.0"
description = "Implementation of controlled rectified stochastic differential equations for image inversion and editing"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.6.0",
    "torchdiffeq>=0.2.5",
]
